# Generated by Django 4.2.18 on 2025-03-11 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='origin',
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
